# Generated by Django 3.0.5 on 2020-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='barber',
            name='locations',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
