# Generated by Django 3.0.5 on 2020-04-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200419_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='user',
        ),
    ]
